# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wdVgKGpHe5jeZ4FqRxPfceis7f3-1tNO
"""

Exercício 1: Escreva um programa que use a função range() para gerar os números pares de 2 a 20 e, em seguida, imprima cada número.

for i in range(2,21,2):
 print(i)

Exercício 2: Escreva um programa que use a função `range()` para gerar os múltiplos de 5 em 5 a 50 e, em seguida, calcule e imprima a soma desses múltiplos.

for i in range(5,50,5):
 print(i)

Exercício 3: Escreva um programa que use a função `type()` para verificar o tipo de uma variável.

n1 = 10
n2 = type(n1)
print(n2)

Exercício 4: Escreva um programa que use a função `print()` para imprimir uma mensagem de saudação personalizada, incluindo o nome do usuário.

n1 = print('Cadastro:')
n2 = input('Digite seu nome -> ')
n3 = input('Digite sua senha -> ')
n4 = print('Saudações,',n2)

Exercício 5: Escreva um programa que use a função `range()` para gerar os números ímpares de 1 a 10 e, em seguida, calcule e imprima a média desses números.

for i in range(1,10,2):
 print('Números ímpares:', i)

1